stages:
- run

run:
  stage: run
  tags:
  - minecraft
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule"
  - when: manual
  image:
    name: python:3.10-slim
  script:
  - pip install -r requirements.txt
  - python main.py
