name: Check Room

on:
  schedule:
  - cron: '*/5 0-17,23 * * *'
  workflow_dispatch: {}

jobs:
  check-room:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run check-room
      run: python3 main.py
      env:
        TLG_BOTTOKEN: ${{ secrets.TLG_BOTTOKEN }}
        TLG_CHATID: ${{ secrets.TLG_CHATID }}
    - name: Send Telegram notification
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TLG_CHATID }}
        token: ${{ secrets.TLG_BOTTOKEN }}
        message: |
          다락휴 확인 실패!
          이벤트: ${{ github.event_name }}
      
